### ISSUE TITLE
Contact Form 7 issue

### ISSUE THREAD

**Issue by motorradfahrer** [bmarshall511/wordpress-zero-spam#102]
hi,

Zero Spam seems to work with Contact Form 7 as long as I keep the standard form with name, email, subject and text. But when I add optional used text fields for example for the address of the sender Zero Spam does no longer allow to send the mail. As soon I deactivate the Zero Spam plugin or just the Contact Form 7 support does it work and the mail is sent.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. With the new version, you should no longer encounter this issue.

Thanks for reporting it!
