### ISSUE TITLE
JS not found when WP_DEBUG = TRUE

### ISSUE THREAD

**Issue by eye8** [bmarshall511/wordpress-zero-spam#106]
Hi, 

I downloaded your plugin from wordpress.org and am evaluating it to be used on our site. I noticed an obvious error. In your zero-spam.class.php, you are including the non-minified JS file if WP_DEBUG is TRUE. However that file is not included in your Grunt build. Please see the screenshot below.

![screen shot 2014-12-11 at 10 00 45 am](https://cloud.githubusercontent.com/assets/1659798/5396151/8a039a3a-811d-11e4-98be-de8eb2f730cb.png)

It's not a big deal for a Wordpress developer as it's easy to identify. But it might for non-devloers. Thanks for fixing.

**Comment by norcross** [comment]
noted as well. also, the version number doesn't match the plugin (unless that's the JS version)

**Comment by A5hleyRich** [comment]
:+1: Non minified versions should be included. The conditional should also use the `SCRIPT_DEBUG` constant.

**Comment by bmarshall511** [comment]
This will be taken care of in the next release.

**Comment by bmarshall511** [comment]
2.0.0 released, this should no longer be a problem.
