### ISSUE TITLE
Multisite Auto Block IP

### ISSUE THREAD

**Issue by Coopeh** [bmarshall511/wordpress-zero-spam#108]
Hi,

There's a problem when the AutoBlock IP setting is enabled if using with Multisite. It will block the IP but not show it in the Multisite settings window log, you have to remove via SQL if it's a false positive. I'm assuming this is because it logs them per site instead of cross-network. It would be good to pull all of the IPs through from all sites and also give the option to block it network wide.

It would also be useful if you could have a timed block instead of permanent.

Cheers,
Ed

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. Auto blocking of IPs hasn't been implemented yet, but will ensure you don't run into this issue when it is.

Thanks for reporting it!
