### ISSUE TITLE
Multisite tables

### ISSUE THREAD

**Issue by thefrosty** [bmarshall511/wordpress-zero-spam#111]
I can't imagine it necessary to have two tables per blog in Multisite. Imagine the amount of additional tables in a network enabled site with thousands of blogs.  

If the tables are necessary I think a global _log and _ip table would suffice.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. Logging is hasn't been reimplemented yet, but will ensure you don't run into this when it does.

Thanks for reporting it!
