### ISSUE TITLE
Support for Formidable Pro?

### ISSUE THREAD

**Issue by pichogve** [bmarshall511/wordpress-zero-spam#112]
Great plugin! is there a way to get it to work under with Formidable Pro?

**Comment by bmarshall511** [comment]
Sorry, I'm just now getting to this, but... life. The past few weeks been working on v4, a complete rewrite of the plugin. Happy to look into support for Formidable Pro, but would need the plugin to test & integrate. If you can shoot me a copy or donate (https://benmarshall.me/donate/) to help continued development of these add-ons, I'll dig in.

**Comment by jaredatch** [comment]
@bmarshall511 the free version of the plugin would probably be sufficient for adding an integration, check out https://wordpress.org/plugins/formidable/ :)

**Comment by bmarshall511** [comment]
@jaredatch Ah perfect must have missed that when I was searching for it. I dig in to see if I can get it integrated.

**Comment by bmarshall511** [comment]
Good news... 5 years late, but WordPress Zero Spam will support Formidable in the next release (v4.9.0)!

**Comment by SiteSpot** [comment]
Thanks Ben!
