### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by AlanSparks** [bmarshall511/wordpress-zero-spam#113]
Hi
I use this plugin on my one site and it works perfectly - no spam.
On my second site it prevents the registration process from completing. Could you possibly help?
Thanks

**Comment by bmarshall511** [comment]
Sure, going to need more information.

**Comment by qwales1** [comment]
Ran into this today. I migrated a site to a new host and all new registrations were being blocked. I'll let you know if I find anything.
