### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds

### ISSUE THREAD

**Issue by Mte90** [bmarshall511/wordpress-zero-spam#115]
In the spammer log i get:

```
Fatal error: Maximum execution time of 30 seconds exceeded in /data/vhosts/mte90.net/httpdocs/wp-content/plugins/zero-spam/lib/zero-spam.class.php on line 519
```

I want to clean the log but is impossible :-/

**Comment by bmarshall511** [comment]
Try to increase the max time on your server or manually delete the data from the zerospam_log table.

**Comment by Mte90** [comment]
The table have 60mb of data, maybe a simple button empty data will not bad.
My hosting don't have disabled the max time settings.

**Comment by 082net** [comment]
It may related to #126

**Comment by bmarshall511** [comment]
This should be fixed now, let me know if you run into anymore issues.
