### ISSUE TITLE
Integration Into Any Form - Through Documentation

### ISSUE THREAD

**Issue by vzeazy** [bmarshall511/wordpress-zero-spam#116]
Hey there,

Looking at the issue queue a lot of people need integration into their own forms. One thing that would be amazing is to simply provide a function or hook that brings zero-spam into any form you wish.

Looking at the code it shouldn't be much different than how's it already implemented for Gravity Forms.

Simply document the process of what is required for zero-spam to do what's needed. Add a function that can pull the required js onto the form page and whatever else is required to be triggered during POST.

This would be huge.

All the best.

**Comment by bmarshall511** [comment]
Great idea! I'll add a class (`zerospam`) that can be added to any form. When added, it'll add the needed JS then the user will just need to write their own hook.

**Comment by vzeazy** [comment]
Happy to contribute. Let me know if you need any help.
Take care.

**Comment by bmarshall511** [comment]
Always looking for good contributors. If you wanna take a stab at it, feel free.

**Comment by bmarshall511** [comment]
Actually, think I've got this one. Thanks though.

**Comment by bmarshall511** [comment]
Just released 2.0.0 which has this included. Thanks for the idea!
