### ISSUE TITLE
Contact Form 7 - Ajax Error

### ISSUE THREAD

**Issue by vzeazy** [bmarshall511/wordpress-zero-spam#118]
Hi Ben,

Thanks for the great work with version 2 (added the hook to a Mailchimp form successfully).
However, was testing something and it looks like there might be some issue with Contact Form 7 now.

On form submission I am getting an ajax error:
"Unexpected token T"

And infinite spinning icon.

However, if I click submit a second time, the form submits.

All the best.

**Comment by bmarshall511** [comment]
Yeah, this is a tricky one. Looks like the hidden form field doesn't get submitted with the AJAX call the first time. It's probably getting called before the code that adds the hidden input get's ran. Which is why it works the second time.

**Comment by bmarshall511** [comment]
Got a fix, will go out hopefully today: https://github.com/bmarshall511/wordpress-zero-spam/pull/119

**Comment by vzeazy** [comment]
That was fast! :)
Issue is gone.
