### ISSUE TITLE
respect https connections to wordpress

### ISSUE THREAD

**Issue by eremo** [bmarshall511/wordpress-zero-spam#122]
I started using zero spam on one of my blogs recently. There is one thing which I think could be improved: 
When you log in to wordpress via https but your blog address is a simple http address the zero spam buttons (at the bottom of the "Spammer Log" page for going through the history of spam actions try to open the next page via http, only. This may require a new unprotected login. 

I suggest that the button links respect https if the present connection to the blog is of https type.

**Comment by bmarshall511** [comment]
@eremo Unable to reproduce. Ensure your site setting have been updated to use https://
