### ISSUE TITLE
Fork link in plugin admin area

### ISSUE THREAD

**Issue by slaFFik** [bmarshall511/wordpress-zero-spam#124]
It leads to https://github.com/bmarshall511/wordpress-zero-spam/fork, which returns 404 if user is logged out. And that is frustrating. 
Is it better to provide the link just to the repo? https://github.com/bmarshall511/wordpress-zero-spam

**Comment by jaredatch** [comment]
@bmarshall511 I tend to agree here, if you want to sneak this into the next update :)

**Comment by bmarshall511** [comment]
@jaredatch Will do.

**Comment by bmarshall511** [comment]
Updated: https://github.com/bmarshall511/wordpress-zero-spam/commit/05a5ffb90cf86b86a4b5e1d1d1d4892d4971f6ec
