### ISSUE TITLE
Protected time in Summary section is wrong

### ISSUE THREAD

**Issue by slaFFik** [bmarshall511/wordpress-zero-spam#125]
I have activated the plugin today, and on Spammer Log page in Summary I see this:

```
Protected
-1 days
```

Which is strange :)

**Comment by slaFFik** [comment]
And here is 1 more:
    Per day
    -5

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. Logging hasn't been reimplemented yet, but will be soon & will ensure you don't run into this issue again.

Thanks for reporting it!
