### ISSUE TITLE
Memory leak on spam log page

### ISSUE THREAD

**Issue by 082net** [bmarshall511/wordpress-zero-spam#126]
I have 500,000 rows on spam log table and when I navigate to 'Spammer Log' tab, there's no spam logs but PHP memory leak message appears.

I've found that's because of SQL query that request all rows in table at once.

"src/ZeroSpam/Admin.php:523"
$all_spam        = zerospam_get_spam();
=> SELECT \* FROM wp_zerospam_log ORDER BY date DESC 

Maybe we better parse logs with not PHP but SQL queries and give them some limits and pagination.

Thanks for your great plugin :-)

**Comment by 082net** [comment]
Attached Instant patch for huge log table

[huge-log-table.patch.zip](https://github.com/bmarshall511/wordpress-zero-spam/files/107125/huge-log-table.patch.zip)

**Comment by bmarshall511** [comment]
@082net Thanks for the contribution.

**Comment by 082net** [comment]
It's my pleasure

Thank you
