### ISSUE TITLE
Log spam errors for ninja forms submissions

### ISSUE THREAD

**Issue by helgatheviking** [bmarshall511/wordpress-zero-spam#128]
I'm having multiple people tell me they can't submit my ninja forms contact form, but the zero spam settings say there should be an error message in the case of a spam submission. Would zero spam prevent certain users from being able to submit a Ninja forms contact form? 

Of course, in typical debug hell, I can submit the form just fine. :) So, instead I was trying to look through the spam logs and there either there isn't a way to look at the NF spam separately or I haven't received any. If the latter is true, I need to look elsewhere for my contact form issues. But if the former was possible it might help me track down some false positives.

**Comment by jaredatch** [comment]
@bmarshall511 I'd go ahead and close this, #130 likely fixed it :)

**Comment by bmarshall511** [comment]
@jaredatch Thanks again!
