### ISSUE TITLE
Integration with WPForms

### ISSUE THREAD

**Issue by jaredatch** [bmarshall511/wordpress-zero-spam#129]
First, big fan of the plugin. Been using it on client sites for a good while with great success 👍 

I have a new and rapid growing forms plugin, WPForms (https://wordpress.org/plugins/wpforms-lite/)

I'd love to get WPForms officially integrated. We currently offer our own honeypot (though not near as complex as WZP) and well as reCAPTCHA support, but would like to integrate with WPZ to offer users another option.

I don't mind whipping up a pull request to do the heavy lifting, just wanted to reach out first, say "hi", and get any feedback.

What you say @bmarshall511? 😀

**Comment by bmarshall511** [comment]
Sounds good to me, go for it!

**Comment by bmarshall511** [comment]
@jaredatch All set, just finished the 2.1.0 release. Thanks again!

**Comment by jaredatch** [comment]
Whoops, looks like the version on .org is 2.1.1 instead of 2.1.0 ;)

Been there, done that. 😆

**Comment by bmarshall511** [comment]
Yeah, forgot to add you as a contrib in the readme file so you show up on the plugin page. Made the update after I released 2.1.0, so did another quick release.
