### ISSUE TITLE
Remove geoip feature

### ISSUE THREAD

**Issue by jaredatch** [bmarshall511/wordpress-zero-spam#131]
Sadly, the freegeoip.net service is gone and and it appears for good. The cost/bandwidth it took was pretty ridiculous apparently.

More info here https://github.com/fiorix/freegeoip/issues/165

While that was a nifty feature for the plugin, I don't think it's going to be easy to find a reliably free replacement (I already looked for another project).

Due to this service being down, right now:

- Spammers log country section does not load (http://cl.ly/2Q2O3g052F37)
- Request to API fails and results in a javascript error

Considering all these things, do you think in the next version we should simply consider removing this feature? Would happy to be to whip up a pull request, then it could be pushed out in a 2.1 with the WPF integration, etc. Let me know.

Since I had time to dig through the plugin, if you don't mind I can create some other misc Issues with things I saw/feedback 🍻

**Comment by bmarshall511** [comment]
@jaredatch Sorry, just saw this one. That's unfortunate, please do remove and feel free to create other pull requests. 

Great site by the way!

**Comment by GeertHauwaerts** [comment]
Or you could just swap to freegeoip.**io** :)

**Comment by jaredatch** [comment]
I thought about that when I saw that thread. But that was setup 19 days ago with a supposed "free" digital ocean account.

My concern is if the switch is made, how long until everyone else hops on board and that service is also overloaded and killed.

We all know in the hosting world nothing is free or unlimited despite what might be said 😉  

Guess we could give it a go and see. Then if that goes away, _then_ pull it.

**Comment by jaredatch** [comment]
For now service has been restored as it looks like the domain was forwarded/proxied to a new server. So we can close this for the time being. I'll keep an eye out.

**Comment by bmarshall511** [comment]
@jaredatch Thanks for the follow up!
