### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ethicalhack3r** [bmarshall511/wordpress-zero-spam#135]
Hi,

The plugin has a serious security issue which was reported to us (wpvulndb.com). I have tried to contact two of the developers via email without success. Just found this Github repository now. WordPress are aware of the issue so they may have contacted you already.

Please email team at wpvulndb.com for the technical details.

Thanks,
Ryan

**Comment by bostonchic** [comment]
Hmm, I tried to delete it on three sites after deactivating and it won't uninstall.

**Comment by jaredatch** [comment]
ping @bmarshall511

**Comment by janemanthorpe** [comment]
Hi,
I had the same issue but deleted via my control panel with Hostgator I am hosted with. Depending who you are hosted with , you need to go into the WP content area, then plugins and then find Zero spam plugin and delete all the files for your directory. Make sure first you have deactivated the plugin from your wordpress dashboard and done a backup first (just in case)  Cheers Jane

**Comment by bostonchic** [comment]
Yes, I deleted via FTP... it's a shame that users who maintain their own site may not understand how to get rid of it.  :(

**Comment by janemanthorpe** [comment]
Yes, you are right. Shame on the plugin creator just abandoning it.

**Comment by geckoseo** [comment]
?? It would be decent at the very least if the reason for the removal from the WP repo was explained on the authors website.

Instead we can apparently still download and use the plugin directly from here?

Is this not somewhat irresponsible? Why would anyone still allow a plugin with security holes in it to be downloaded?

**Comment by thiagolcks** [comment]
I've made a PR to fix this issue.

**Comment by bmarshall511** [comment]
@thiagolcks Thanks for the help, haven't had time to devote to it. Just submitted the plugin again to get back in the repo.

And @geckoseo and @janemanthorpe how about instead of bitchin' you contribute... shame shame. Try looking up what open source means.
