### ISSUE TITLE
Uninstall Issue

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [bmarshall511/wordpress-zero-spam#136]
Hello!

I tried to temporarily remove your plugin until [this security issue](https://wpvulndb.com/vulnerabilities/8608) is resolved and I noticed the uninstall fails. After a little digging, I found that some of the checks in the uninstall.php file are failing, causing the uninstall to end prematurely.
My tests suggest that there is a combination of checks that return false since the plugin uninstalled correctly only after I removed them all. ( Removing one check at a time made no difference )

Best regards,
Eusebiu Oprinoiu

**Comment by bmarshall511** [comment]
This will be fixed in the next release thanks to @thiagolcks
