### ISSUE TITLE
Is this project over?

### ISSUE THREAD

**Issue by katart** [bmarshall511/wordpress-zero-spam#137]
I don't see this plugin in the Wordpress Plugin repo and no responses here. The last issue I noticed is the Security problems.

Should I look for a different plugin?

**Comment by jaredatch** [comment]
For the time being it's probably best.

I think @bmarshall511 likely got busy with life or possibly doesn't work with WordPress much anymore.

Hopefully he's OK and he can provide an update and some point!

The good news is there are similar alternatives on the WordPress.org repo

**Comment by katart** [comment]
Good point. We hope to hear from him soon just to let us know he's OK.

It did look like he was working with Drupal as well. Thanks @jaredatch
