### ISSUE TITLE
Ability to whitelist IP address

### ISSUE THREAD

**Issue by jonkratz** [bmarshall511/wordpress-zero-spam#141]
This is a feature request: the ability to whitelist an IP address for submissions without needing js. One use case for this is automated form testing that is legitimate but looks like spam. You could whitelist the IP where the testing is coming from.

**Comment by jpBenfica** [comment]
Recently I got my IP blocked, it would be important to add a white IP list.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. With the new version, you should no longer encounter this issue.

Thanks for reporting it!
