### ISSUE TITLE
Conflict with WPI CLI

### ISSUE THREAD

**Issue by vzeazy** [bmarshall511/wordpress-zero-spam#142]
Hi Ben,

Not sure where the conflict is exactly, but the the plugin results in "Access Denied" being thrown by WP_CLI. This is very unfortunate as it is a key tool for most developers.

Some potential leads on to what's causing the issue:
https://github.com/wp-cli/wp-cli/issues/477

In the meantime, I'm stuck using "--skip-plugins=zero-spam" to execute wp_cli commands.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. With the new version, you should no longer encounter this issue.

Thanks for reporting it!
