### ISSUE TITLE
No zerospam field created for CF7

### ISSUE THREAD

**Issue by bit9labs** [bmarshall511/wordpress-zero-spam#144]
I installed the Zero Spam plugin and have CF7 installed. I enabled the CF7 support in Zero Spam, but do not see any zerospam element in the form. When looking through the code I only see the validation check to see if the $_POST['zerospam'] is there. 
Please assist? Is this a field i have to add manually?

**Comment by bmarshall511** [comment]
That field is added only when the form is submitted, so no, don't need to add it manually.

**Comment by bit9labs** [comment]
Ok I see it now in zerospam.js. Thank you.
