### ISSUE TITLE
If IP Auto Block is on and the IP is UNKNOWN - all access to site will be blocked

### ISSUE THREAD

**Issue by smfatwork** [bmarshall511/wordpress-zero-spam#146]
We have a site in an environment where the function zerospam_get_ip() is returning UNKNOWN for all requests, once a form submission was determined to be spam it added a block for the IP "UNKNOWN" and from that point on all access to the site from all IPs was blocked.

Possibly an activation check for the ability to get ip and/or not adding a block for IP if the IP is "UNKNOWN"?

We've turned off IP auto block for now.

**Comment by bmarshall511** [comment]
Hopefully this will fix your issue: https://github.com/bmarshall511/wordpress-zero-spam/pull/143
