### ISSUE TITLE
conflict blocking cron jobs?

### ISSUE THREAD

**Issue by Typiary** [bmarshall511/wordpress-zero-spam#166]
Hi Ben,

I've used your plugin for years and love it. I've never had an issue like this. On my site running WooCommerce and the WC Subscriptions plugin, I noticed that some parts of the Subs admin were not updating. Investigation by my server/host and WooCommerce support found that the cron was stalled so scheduled events weren't happening. We looked for PHP errors in the logs, nothing seemed wrong.

When I deactivated/re-activated plugins one by one to check for conflicts... bingo: deactivating WP Zero Spam immediately started the cron and my scheduled events updated. I'm not a good enough developer to go deeper, but I'm wondering if there are other reports, or if you have any insight here, or if it's possible to update the plugin to address this issue – so I can go back to using it! Thanks.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. With the new version, you should no longer encounter this issue.

Thanks for reporting it!
