### ISSUE TITLE
Auto IP Block accidentally bloks all IPs

### ISSUE THREAD

**Issue by Bobo8** [bmarshall511/wordpress-zero-spam#167]
Hi, once a year my web is inaccessible to (I think) everybody (there is only message form Blocked IP Message). When I am logged in then the web works.

If I remember well, last time I solved it by clearing the (Comet) cache. Now I solved it by setting Blocked IP Message off and disabling and enabling the cache. Even when I set it on, then the web works.
I understand, that it doesn't help you much as its not possible to reproduce it.
Everything updated, 34 plugins.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. With the new version, you should no longer encounter this issue.

Thanks for reporting it!
