### ISSUE TITLE
Compatability with Astra theme

### ISSUE THREAD

**Issue by viktorix** [bmarshall511/wordpress-zero-spam#168]
Astra theme changes comment form's ID to `#ast-commentform`, which makes it incompatible with Zero Spam since it has `#commentform` ID hardcoded.

It would be great if there was an option to specify a custom ID for the comment form in the settings. Or at least add `#ast-commentform` to the list, since the Astra theme is very popular.

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Finally had some time to update the plugin & did a complete rewrite with version 4. I've included your findings in the new version as of v4.1.1.

Thanks for looking into that!
