### ISSUE TITLE
Log "skip to end" button actually skips back to page 1

### ISSUE THREAD

**Issue by DavidMillington-CD** [bmarshall511/wordpress-zero-spam#169]
Hi, when I click the >> at the bottom of the log the expected behavior is for it to jump to the final page.  Instead it jumps back to page 1.  Reproduced on 3 different sites.

Plugin v 3.1.1

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Just did a complete rewrite of the plugin for v4. Logging isn't there yet, but will be coming soon & will ensure you don't run into this kind of issue again.

Thanks for reporting it!
