### ISSUE TITLE
Possible technical bug with Ninja Forms

### ISSUE THREAD

**Issue by cmgustin** [bmarshall511/wordpress-zero-spam#171]
I installed the latest version of the plugin on a couple of my client sites last week since they were getting a barrage of spam in Ninja Forms. I checked in a few days later and noticed they were still getting spam, which I thought was strange since this plugin has worked really well for my Gravity Forms sites.

I dug into the code a little and noticed 2 possible issues. In the file 'js/zerospam.js':

1. The jQuery selector used to target Ninja Forms doesn't appear to be valid. The code is using `.ninja-forms-form` but running a query for this selector from the console on a page running Ninja Forms turned up no results. I tried patching this by changing to a selector that exists but spam was still getting through
2. After a little more research, it turns out Ninja Forms loads asynchronously, which means you can't bind to it with `$(document).ready` and instead have to use their custom event `$(document).on('nfFormReady')`. I tried updating my plugin with the following code, right after line 23 in 'js/zerospam.js':
```
$(document).on('nfFormReady', function(e, layoutView) {
  var form = layoutView['$el'].find('form');
  $("<input>").attr("type", "hidden").attr("name", "zerospam_key").attr("value", zerospam.key).appendTo(form);
  return true;
}); 
```
I checked the sites today however and I'm still seeing spam coming through. Any thoughts on where to go from here?

**Comment by bmarshall511** [comment]
I know it's been awhile, but... life. Finally had some time to update the plugin & did a complete rewrite with version 4. I've included your findings in the new version as of v4.1.1.

Thanks for looking into that!
