### ISSUE TITLE
Support for Caldera Forms

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#174]
https://wordpress.org/support/topic/does-this-plugin-work-with-caldera-forms/

**Comment by SunfireWeb** [comment]
I have a client using Caldera Forms and receiving a lot of spam lately. I like and appreciate this Zero Spam plugin, and would like to apply it to my client's sites, IF I know it would actually help in this case. Thanks for considering.

**Comment by bmarshall511** [comment]
Closing, Caldera Forms is going away on Dec. 31 2021. See https://calderaforms.com/2021/03/the-future-of-caldera-forms/
