### ISSUE TITLE
Admin settings PHP notices

### ISSUE THREAD

**Issue by jaredatch** [bmarshall511/wordpress-zero-spam#175]
Activating v4.1 on a fresh WP install triggers PHP notices when viewing the ZS admin settings.

```
Notice: Undefined index: log_blocked_ips in /wp-content/plugins/zero-spam/inc/admin.php on line 222
Notice: Undefined index: blocked_ips in /wp-content/plugins/zero-spam/inc/admin.php on line 249
```

**Comment by afragen** [comment]
Saving preferences should fix this.

**Comment by bmarshall511** [comment]
@jaredatch Thanks again! Submitted another fix into master (https://github.com/bmarshall511/wordpress-zero-spam/commit/da0659daa66e45208340c9bc754d10bc507ec49b).
