### ISSUE TITLE
Caching conflicts

### ISSUE THREAD

**Issue by jaredatch** [bmarshall511/wordpress-zero-spam#177]
In the v4.x update, I see that the key logic was changed. I see what you're doing, trying to be a bit more creative to combat the spammers. But with that said, I _think_ this may be a breaking change for a large portion of WPZS users, possibly the majority.

Prior to the 4.x release, WPZS used an option to store the key.

In 4.0, this changed to rely on cookie tracking. The issue is the cookies are set serverside, which will not work with most caching setups.

Here's an example.
- (Cache is not set or expired)
- Bob visits acme.com, cache is expired so things proceed as you'd expect....
- PHP generates and builds the Contact Page.
- When contact page loads, it creates 64 char `key` - then outputs it on the page via localize_script and cookies Bob via PHP. Let's say key is 12345.
- After this page loads, it's cached (varnish, nginx, wp-rocket, whatever).
- (Cache is now primed)
- Bill visits acme.com, cache is primed so he is served the cached page.
- The Contact Page loaded from cache and includes the previously generated key, 12345.
- Because PHP didn't have to generate the whole page (or potentially run at all), the cookie is never set for Bill.
- Bill submits contact form, the passed cached key of 12345 won't match the cookie because it doesn't exist, so validation will fail.

**Comment by bmarshall511** [comment]
@jaredatch Good point! I've updated it so it no longer uses cookie, instead goes back to using the site option. Let me know if you see any problems going that route (in master): https://github.com/bmarshall511/wordpress-zero-spam/issues/177
