### ISSUE TITLE
Re-implement logging

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#181]
v3 of the plugin provided logging & statistics. Need to re-implement in v4.

**Comment by bmarshall511** [comment]
@jaredatch I'm gonna have a big commit for this soon. Wondering if you would mind testing it all to make sure all goes well?

**Comment by jaredatch** [comment]
Sure a can take a look tomorrow.

**Comment by bmarshall511** [comment]
@jaredatch Think I'm ready now. Ran into an issue with older version on MySQL not supporting the JSON datatype, but just threw up a fix. As soon as you give me the green light, I publish a new release.

**Comment by bmarshall511** [comment]
@jaredatch Thanks for digging into that! Just pushed an update that resolves most of what you found. Think we're ready to publish a new release now? Would like to get logging enabled ASAP so user's can at least start collecting that data. Future updates will include more functionality & reporting based on it.

**Comment by jaredatch** [comment]
Changes look good. You're doing great iterating quickly 😎

**Comment by bmarshall511** [comment]
Thanks! Just release v4.2.0 in the repo. Keeping fingers crossed. Closing this for now. Will start working on the addition of stats & ability to add/automate blocked IPs
