### ISSUE TITLE
Last update creates fatal error

### ISSUE THREAD

**Issue by nam1962** [bmarshall511/wordpress-zero-spam#182]
Hi, thank you for your work that I use for years.
Here a problem I had on my sites with the last update : 
```
Fatal error: Uncaught LogicException: Function 'zerospam_autoloader' not found (function 'zerospam_autoloader' not found or invalid function name) in /home/meco/public_html/mysite.com/wp-content/plugins/zero-spam/zero-spam.php:54Stack trace: #0 /home/meco/public_html/mysite.com/wp-content/plugins/zero-spam/zero-spam.php(54): spl_autoload_register('zerospam_autolo...') #1 /home/meco/public_html/mysite.com/wp-settings.php(371): include_once('/home/meco/...') #2 /home/meco/public_html/mysite.com/wp-config.php(83): require_once('/home/meco/...') #3 /home/meco/public_html/mysite.com/wp-load.php(37): require_once('/home/meco/...') #4 /home/meco/public_html/mysite.com/wp-blog-header.php(13): require_once('/home/meco/...') #5 /home/meco/public_html/mysite.com/index.php(17): require('/home/meco/...') #6 {main} thrown in /home/meco/public_html/mysite.com/wp-content/plugins/zero-spam/zero-spam.php on line 54
```
I had the same error with various configurations : apache or litespeed, litespeed with and without lscache.
php 7.4

**Comment by bmarshall511** [comment]
That looks like you still might be using the older v3 plugin. That call it only used in the older version, the newer version doesn't have that. Try deleting the plugin folder for wordpress zero spam, then reinstalling

**Comment by nam1962** [comment]
Oh yes !
That's strange : all my sites had the problem, whether fatal error, or deactivated zero spam.

I had to ftp rename the directory as "zero_spam.bak", then manually update (I usually use `add_filter( 'auto_update_plugin', '__return_true' ); // Plugins` ) and had 4.1.2 & 4.1.3 updates.

With 4.1.3 no fatal error, but 3 problems : 
1. into the void disappeared in favor of a goo redirection, that's awful : I don't want to risk redirecting irrelevant to them : they might not like it (meanwhile I redirect to a non existent URL, but it is totally suboptimal.)
2. new version totally erased my personal error messages :/
3. I don't see any log any more and lost all previous log :/
Additional problem : I have to totally rewrite my tuto on Zero Spam : https://dolys.fr/forums/topic/optimisation-securiser-wordpress/

Do you plan to correct these and to inform ?

**Comment by bmarshall511** [comment]
1. This is configurable via WP Zero Spam > Settings. You have the ability to choose redirect you throw a 403 Forbidden error.
2. Yeah, unfortunately this rewrite is literally a complete rewrite in favor of emerging trends, cleaner code and new WP features since the original build of the plugin.
3. Logging is going to be re-implemented in the next release, hopefully sometime today.
