### ISSUE TITLE
Long time user...  4.2.0 is sending eMails for each spam

### ISSUE THREAD

**Issue by barteelamar** [bmarshall511/wordpress-zero-spam#186]
4.2.0 is sending eMails for each spam

What do I have to do to fix this.   It worked perfect in 4.1.3   Never had spam...

**Comment by bmarshall511** [comment]
Hey @barteelamar , this plugin has never sent email including the latest version. It' most likely something else you've got installed. Can you provide me an example of the email you're getting?

**Comment by bmarshall511** [comment]
Closing this as it's unrelated to what the plugin does.
