### ISSUE TITLE
Error for undefined constant in v4.3.2

### ISSUE THREAD

**Issue by afragen** [bmarshall511/wordpress-zero-spam#189]
I just updated to v4.3.2 and now I see the following error.

`Warning: Use of undefined constant REFERRER_ANALYTICS - assumed 'REFERRER_ANALYTICS' (this will throw an Error in a future version of PHP) in /sites/xxxxx.xom/files/wp-content/plugins/zero-spam/inc/scripts.php on line 17`

Thought you should know.

**Comment by bmarshall511** [comment]
Thanks! Just pushed a fix up in v4.3.3: https://github.com/bmarshall511/wordpress-zero-spam/commit/b830122a793cd0773bcd4e26bbc590eb7ef318ba
