### ISSUE TITLE
Integrating with Sunny v1.4.11

### ISSUE THREAD

**Issue by TangRufus** [bmarshall511/wordpress-zero-spam#19]
The latest version (v1.4.11) of [Sunny](wordpress.org/plugins/sunny/) provides support for Zero Spam.
Sunny tells CloudFlare to ban an IP if Zero Spam blocks a spammy comment or spammy registration.

Do you think it is good to include a notice about Sunny in the `README` file?

**Comment by bmarshall511** [comment]
2.0.0 released which includes this. Thanks!
