### ISSUE TITLE
Conflict Between Latest Release and Visual Composer WP Bakery

### ISSUE THREAD

**Issue by wwwebdesignstudios** [bmarshall511/wordpress-zero-spam#190]
WP Bakery on page edits no longer shows, when i deactivate wordpress zero spam, the page builder now shows.  I downloaded the latest version of WP Bakery just to make sure and the latest of your plugin

**Comment by wwwebdesignstudios** [comment]
version 4.3.1 works but not version 4.3.3

**Comment by bmarshall511** [comment]
Hmm, strange. The plugin shouldn't effect the editor since it doesn't touch it at all. Since WP Bakery is a premium plugin that I don't have, unable to test. Could you provide more details? Are there any JS errors, anything in the error_logs, screenshots, etc.?

**Comment by wwwebdesignstudios** [comment]
i can send you a zip of the latest release for your to test?  let me know and i can attach.

**Comment by bmarshall511** [comment]
Sure, you can send it to me@benmarshall.me.

**Comment by wwwebdesignstudios** [comment]
ok another note - i tested this issue on two completely separate websites just to make sure it wasn't some other conflict.  Once i uploaded the 4.3.1 version the wpbakery page builder went back to normal

**Comment by bmarshall511** [comment]
@wwwebdesignstudios Just wanted to check in on this & if you were able to send me a copy of the page builder.

I just released 4.3.4, which modifies when the Zero Spam plugin loads its JS (now only loads when on one of the Zero Spam specific pages). No clue if it's related, but thought I'd mentioned incase you update & see that it's no longer a problem.

If you do update to 4.3.4, would love to know if you're still experiencing this issue.

**Comment by wwwebdesignstudios** [comment]
i emailed you the plugin yesterday - did you receive it? it was a zip file jcomposer.  I will test 4.3.4 in the meantime. Thanks.

**Comment by bmarshall511** [comment]
@wwwebdesignstudios Nope, never got it.

**Comment by wwwebdesignstudios** [comment]
I just sent it again to 'me@benmarshall.me'

 

 

 


Walter Keener
Web Design & Marketing Coordinator
WW Web Design Studios

o: 954-543-8736
t: 888-790-5505
e:  <mailto:walter@wwdesignstudios.com> walter@wwdesignstudios.com

**Comment by bmarshall511** [comment]
@wwwebdesignstudios Thanks, got it that time. I installed & checked with the latest version (v4.3.6) of zero spam & all works for me. See attached screenshots. Let me know if you're still running into it after you update.

![image](https://user-images.githubusercontent.com/1920159/87994743-57402600-cab3-11ea-9213-fb033c9a61de.png)

![image](https://user-images.githubusercontent.com/1920159/87994806-7dfe5c80-cab3-11ea-8cd0-feeb8c9e17b8.png)

**Comment by wwwebdesignstudios** [comment]
thank you - i believe what you have changed in this version has allowed the page builder to function normally again.  thanks again for your help!

**Comment by bmarshall511** [comment]
Perfect! Glad it got resolved & thanks again for letting me know about it!
