### ISSUE TITLE
Integrate Genesis comment system

### ISSUE THREAD

**Issue by maryannk** [bmarshall511/wordpress-zero-spam#198]
My sites that are running this plugin are suddenly not filtering spam comments that used to be filtered. This is just since yesterday. Because they contain links, they are being held for moderation due to my settings, but they are no longer being marked as spam by the plugin. I'm not getting spam contact submissions, just comments.

Site 1:
WordPress 5.4.2 
Genesis 3.3.2 with a custom child theme
WP Zero Spam Version 4.3.9 
Default Genesis comment system

Site 2: 
WordPress 5.4.2
Genesis 2.10.1
WP Zero Spam Version 4.3.9 
Default Genesis comment system

Let me know if there is any additional information that would be helpful.

**Comment by bmarshall511** [comment]
The Genesis framework isn't currently supported. Updating this to a feature request as this isn't a bug.

**Comment by bmarshall511** [comment]
@maryannk  It appears that Genesis is a premium theme. I don't have it so unable to attempt to integrate. If you can provide me a copy & whatever they require to set up, I'll take a look at it.

**Comment by maryannk** [comment]
Thanks for following up, Ben. I'm not sure I can provide a copy of Genesis under the terms of my license so I guess I'll let this drop. I appreciate your willingness to attempt it.

**Comment by bmarshall511** [comment]
Not a problem. I also accept donations to continue open-source projects like these. It's how I'm able to purchase premium versions on plugins & provide pro-Bono for nonprofits in case you're interested: https://benmarshall.me/donate/

**Comment by maryannk** [comment]
Donated. It won’t buy the Genesis framework but I appreciate the use I’ve gotten from your plugin up until now.

**Comment by bmarshall511** [comment]
Thanks! I really appreciate it, especially with all the craziness going on right now. I'm gonna keep this ticket open & will try to be it integrated at some point.

Thanks again!

**Comment by bmarshall511** [comment]
@maryannk I forgot to mention, this plugin will still be helpful on your site. The last update has some more spam detection functionality unrelated to forms. Integrated with known blacklisted API services & some on-site security settings that'll help protect the site. More is coming in this area, so still definitely worth it.

**Comment by maryannk** [comment]
Thanks, Ben. I’m definitely keeping it active. These are smaller sites that don’t have as much of a spam problem as my larger ones and I’m sure having it active will help even if some get through.

**Comment by jaredatch** [comment]
@bmarshall511 I'm a Genesis license holder and I can share the framework with you if needed, it's GPL license.

With that said, I also have much experience with Genesis and from my recollection they pretty much use the vanilla WordPress comment system, so I can't think of any reason off the top of my head why WPZS wouldn't function as expected when the site is using a Genesis based theme.

**Comment by bmarshall511** [comment]
Yeah, that'd be great. If it is just using the core WP comment system, maybe a simple fix. @maryannk Can you shoot me a link to your site where there's a comment form. Have a hunch the theme may just be overriding the default comment form ID. If so, easy fix.

**Comment by maryannk** [comment]
https://www.censustools.com/transcribe-census-records/ <https://www.censustools.com/transcribe-census-records/>

**Comment by maryannk** [comment]
I’m using a slightly modified version of the Minimum Pro theme but no customizations to the comment form from Minimum Pro that I recall.

**Comment by jaredatch** [comment]
@bmarshall511 email sent.

**Comment by bmarshall511** [comment]
@jaredatch Thanks!

@maryannk I just tested it out on the Minimum Pro theme that @jaredatch shot me. All worked as expected. Looking at your site, my guess is you don't have 'Verify Comments' turned on. 

You can look in the browser console & Zero Spam will display what & how many forms were detected on the page you're on. Your site shows that you have the CF7 option turned on, but isn't showing the message for the comments. Can you double-check that Verify Comments is checked in the settings?

**Comment by maryannk** [comment]
> Can you double-check that Verify Comments is checked in the settings?

@bmarshall511 - yes, all of the boxes are checked including Verify Comments.

**Comment by bmarshall511** [comment]
@maryannk Strange, it should display a message in the console then about if & how many comment forms it found on the page. Stranger because the other checks seem to work like CF7 which tells me the script is firing as it's supposed to. 

Maybe try resaving the settings, might have got stuck in a weird state during the updates.

**Comment by maryannk** [comment]
@bmarshall511 I resaved the settings.

**Comment by bmarshall511** [comment]
@maryannk Looks like that did it, just simulated a spam comment, it caught it.
