### ISSUE TITLE
Zero-spam is blocking me from my own website

### ISSUE THREAD

**Issue by dadon789** [bmarshall511/wordpress-zero-spam#204]
Hello,

Thanks for your great plugin. However, since the update, i have been experiencing this issue though i have not enabled the auto-block ip function. Zero-spam is blocking my ip from accessing my website from the front-end. I am able to login to the admin side perfectly. However, when i try to review the website from the front-end i'm told my ip has been blocked? Can you fix this issue?

**Comment by bmarshall511** [comment]
You have the ability to delete blocked IPs from the setting page. Find your IP in the table then delete it.

**Comment by bmarshall511** [comment]
@dadon789 With the release of 4.8.0, you can now also whitelist IPs to avoid getting blocked. See the settings page.
