### ISSUE TITLE
Autoptimize plugin compatibility

### ISSUE THREAD

**Issue by publicarray** [bmarshall511/wordpress-zero-spam#205]
Hi thanks for the plugin. I just wanted to make people aware that if they use the JavaScript optimisation in [Autoptimize](https://github.com/futtta/autoptimize/) to add `wp-content/plugins/zero-spam` to the whitelist.

It took me too long to realise that all messages where marked as spam using [wpforms](https://wordpress.org/plugins/wpforms-lite/) and zero-spam.

**Comment by bmarshall511** [comment]
Hey @publicarray , thanks for letting me know. The next version (4.9.11) converts the JS to a jQuery plugin that should hopefully resolve the issue. I'll leave this open for now until the next version is released so you can let me know if it fixed the issue.

**Comment by bmarshall511** [comment]
Confirmed that WPForms, WPZS & Autoptimize (JS aggregation on) all work together in the upcoming version. Thanks again for bringing this to my attention.

**Comment by bmarshall511** [comment]
Closing this, confirmed fix in v4.9.11

**Comment by publicarray** [comment]
@bmarshall511 Thank you for the quick reply and solution. I don't follow how using jQuery will fix it. But thanks.
