### ISSUE TITLE
Caching 'Blocked due to spam'

### ISSUE THREAD

**Issue by AmibeWebsites** [bmarshall511/wordpress-zero-spam#208]
Hi, I'm getting situations where totally legit visitors are sometimes unable to access pages, instead seeing a message that they can't access the page due to SPAM activity.

I don't believe they're actually being blocked but are possibly seeing a cached page of a prior block. Is that possible? And if so, how I would I prevent this from happening. I'm using 

Thank you.

**Comment by bmarshall511** [comment]
It's doubtful they are seeing a cached page. I'd need more information to look into. Check to see if the visitor's IP addresses appear in your blocked list, then you'll be able to tell why they were blocked. You can also check the blacklist to see if their IP has been flagged by one of the 3rd-party services like Stop Forum Spam.

**Comment by bmarshall511** [comment]
Closing this for now, not enough information.

**Comment by AmibeWebsites** [comment]
Hi, this has happened again.

While logged in the page works fine.
Logged out I'm getting the "Blocked Message", and so are others, all with different IP addresses.

I cleared the cache and the page works again for everyone.

The cache plugin being used is W3 Total Cache.

Is there a way to prevent "Blocked Message" responses being cached?

Thank you.
