### ISSUE TITLE
Number and names of set cookies not consistent to description (FAQ)

### ISSUE THREAD

**Issue by enton8** [bmarshall511/wordpress-zero-spam#214]
According to the FAQ:
"Only one cookie is stored (**wpzerospam_api_blacklist**)[...]"

This is however not the case. In my current initial installation three cookies are created:
wpzerospam_ip_checked
wpzerospam_has_access
wpzerospam_access_checked

When I look into the code, there are even more cookies that are created at some point:
in file **class-wpzerospam.php**
``	public function set_access_cookies( $access ) {
sets all of these as cookies:
> $access = array(
> 			'ip_checked'     => $ip,
> 			'has_access'     => true,
> 			'access_checked' => false,
> 			'cached'         => false,
> 			'blacklist_api'  => false,
> 			'attempts'       => false,
> 
> );

i.e. wpzerospam_ip_checked, wpzerospam_has_acces, wpzerospam_access_checked, wpzerospam_cached, wpzerospam_blacklist_api, wpzerospam_attempts.

Note also that the blacklist cookie is called differently than in the description.

**Comment by bmarshall511** [comment]
Yeah, the cost of constant updates trying to keep documentation updated as well. Going to be moving this over to the plugins documentation page, https://benmarshall.me/wordpress-zero-spam to make it easier & quicker to update. Feel free to help contribute, by forking the repo and submitting a pull request for these types of updates.

Cookies also may be going away in a future version to better lockdown detections, see https://github.com/bmarshall511/wordpress-zero-spam/issues/215 for more information.

**Comment by bmarshall511** [comment]
Closing this, cookies are no longer used as of v5.
