### ISSUE TITLE
IP address is personal data - GDPR/CCPA

### ISSUE THREAD

**Issue by viktorix** [bmarshall511/wordpress-zero-spam#216]
I noticed in the new version of the plugin there is an option to share spam detections: "Help support WordPress Zero Spam and strenghten its ability to detect spammers by sharing spam detections. The only data that's shared is the IP address, type & site where the spam was detected. Absolutely no personal data is shared."

Under [GDPR](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/key-definitions/what-is-personal-data/)/[CCPA](bclplaw.com/en-US/insights/privacy-faqs-is-an-ip-address-considered-personal-information.html), an IP address of a user is personal data, and having this option enabled by default violates GDPR. So I would recommend two things:

1. Make it opt-in by default, uncheck the box.
2. The wording of the help text should include mention of GDPR/CCPA, something like: "Help support WordPress Zero Spam and strengthen its ability to detect spammers by sharing spam detections. The only data that's shared is the IP address, type & site where the spam was detected. No personal data is shared. However, user's IP address may be considered personal data under GDPR and CCPA."

Not only the site owner would be liable under the privacy laws, but this includes you since you're storing IPs.

Thought I mention this.

**Comment by bmarshall511** [comment]
Thanks for the info! I'll definitely update it in the upcoming version.

**Comment by krugmedien** [comment]
Hi. :-) If "**BotScout API Key**" is unfilled and "**Stop Forum Spam**" is unchecked, the IP-address is send to noone, correct?
