### ISSUE TITLE
[Feature] Ability to disable User agent whitelist feature

### ISSUE THREAD

**Issue by publicarray** [bmarshall511/wordpress-zero-spam#219]
I appreciate the idea behind the feature but because there are [bots claiming to be Googlebot](https://blogs.akamai.com/2014/07/search-engine-impersonation-the-wolf-in-sheeps-clothing.html), I rather have Google's IPs verified with a [reverse IP lookup](https://support.google.com/webmasters/answer/80553?hl=en) or have the ability to disable the user agent feature if/when it gets abused by imposter bots. 

Thanks So much for this plugin! Keep fighting the good fight, This plugin solves the spam problem without the need to add CAPTCHAs.

**Comment by bmarshall511** [comment]
@publicarray Not really clear what you're asking here. Title says 'Ability to disable User agent whitelist feature', but there is no user agent whitelist feature in this plugin. Maybe you can clarify and then will reopen the request if applicable.

**Comment by publicarray** [comment]
I don't know the state of the plugin now, but in an earlier version any user agent that matched google would bypass the some checks. And this was just a request to disable or at least check that the bot is actually google. User agents are only good blacklisting but useless as a whitelist since anyone can pretend to be anyone
