### ISSUE TITLE
Please add WooCommerce support

### ISSUE THREAD

**Issue by pacmanito** [bmarshall511/wordpress-zero-spam#222]
Hi, would be great if you add support for WooComemrce registration form.

**Comment by bmarshall511** [comment]
@pacmanito Will look into. From what I remember, WooCommerce uses the default WP registration form. Can you provide a URL where this form is so I can see what's different about it?

**Comment by pacmanito** [comment]
I suppose they use their own form. It usually have an URL shopadress.com/my-account, here's an example from storefront demo page - https://themes.woocommerce.com/storefront/my-account/

**Comment by bmarshall511** [comment]
Thanks for the idea. The next release will include this functionality.
