### ISSUE TITLE
Add Support for Nginx Caching

### ISSUE THREAD

**Issue by DynAggelos** [bmarshall511/wordpress-zero-spam#223]
I'm using DreamHost's caching plugin [Proxy Cache Purge](https://wordpress.org/plugins/varnish-http-purge/), and when checking the caching on any given page, I get an error whenever WP Zero Spam is activated. It looks to me like some cookies set by WP Zero Spam may be the culprit. Here is what I see from the cache check page.

![caching check](https://user-images.githubusercontent.com/35944457/93504289-e6649100-f8de-11ea-97f5-79886b39b29a.JPG)

In addition, from the JavaScript console I see the following:

```
Cookie “wpzerospam_cached” has been rejected because it is already expired.

Cookie “wpzerospam_blacklist_api” has been rejected because it is already expired.

Cookie “wpzerospam_attempts” has been rejected because it is already expired.

Some cookies are misusing the recommended “SameSite“ attribute

    Cookie “wpzerospam_ip_checked” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

    Cookie “wpzerospam_has_access” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

    Cookie “wpzerospam_access_checked” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

    Cookie “wpzerospam_cached” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

    Cookie “wpzerospam_blacklist_api” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

    Cookie “wpzerospam_attempts” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Conclusion**
Is there anything you can do about these cookies? Perhaps first just try using the correct SameSite attribute? I'm not very familiar with cookies myself.

**Comment by bmarshall511** [comment]
@DynAggelos Yeah, I'm looking into killing the cookie requirement although due to them causing some issue with certain hosts and caching. Will track the progress in this ticket.

**Comment by jaredatch** [comment]
I'm not sure what's going on but I'm not aware of any issues or restrictions of cookies and nginx plus/varnish caching, unless you're trying to read/set the cookie on cached page load via PHP.

I suspect this is a false positive and this plugin shows warning for any cookies, even if it doesn't affect actual caching functionality if the cookies are done in a way that works with caching.

**Comment by DynAggelos** [comment]
> I suspect this is a false positive and this plugin shows warning for any cookies, even if it doesn't affect actual caching functionality if the cookies are done in a way that works with caching.

That may be the case. I've run another Spotlight scan with and without the plugin activated. It doesn't seem to have any considerable difference either way, now that you mention it. However, it would be nice to remove the browser warning about the cookies. I _think_ that can be done by changing [this line](https://github.com/bmarshall511/wordpress-zero-spam/blob/db4e31afd95d6b25e0b8e3e12d79bcc66805e6a3/classes/class-wpzerospam.php#L938) from

``setcookie( 'wpzerospam_' . $cookie_key, $value, $expiration, COOKIEPATH, COOKIE_DOMAIN );``

to

``setcookie( 'wpzerospam_' . $cookie_key, $value, [' expires' => $expiration, 'path' => COOKIEPATH, 'domain' => COOKIE_DOMAIN, 'samesite' => 'Lax' );``

See:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
* https://www.php.net/manual/en/function.setcookie.php

**Comment by bmarshall511** [comment]
v5 was just released and no longer uses cookies. Closing.
