### ISSUE TITLE
ipstack settings missing from Settings page

### ISSUE THREAD

**Issue by pdgitindia** [bmarshall511/wordpress-zero-spam#226]
The **Dashboard** gives a message **Enter your _ipstack API Key_ to enable the world mp view of spam detections**.
On clicking the link the **Settings** page opens.
However, there is no place to add the ipstack API key.

**Comment by bmarshall511** [comment]
Unable to replicate, can you provide a screenshot?

**Comment by incubateurdigital** [comment]
Hello, i have the same issue : 

![image](https://user-images.githubusercontent.com/51329265/100458738-8bac9a00-30c4-11eb-980e-2ba89c85c2aa.png)

and when we click on it, we arrive on zero spam settings, with no option to set this API KEY.
We only have option to set Botscout API Key. 

If Botscout API Key is defined, we still have the message that says we need ipstack API Key.

**Comment by incubateurdigital** [comment]
![image](https://user-images.githubusercontent.com/51329265/100459099-2907ce00-30c5-11eb-8d0a-26ef8e3fcde2.png)
Here is the settings page.

**Comment by collincondray** [comment]
Try clicking the Log Blocked IPs option and see if it shows up then.

**Comment by incubateurdigital** [comment]
@collincondray you're true, this make it display ! ( after save ).
But this is not really clear. Could be improved.

**Comment by bmarshall511** [comment]
Non-issue, closing.
