### ISSUE TITLE
Add ability to block a country

### ISSUE THREAD

**Issue by grand-lotus-iroh** [bmarshall511/wordpress-zero-spam#227]
how do i block an entire country? instead of just a single IP, this one site is getting blasted by Russia so I would like to just block the entire nation of Russia.

any ideas on how I can do this?

**Comment by grand-lotus-iroh** [comment]
Yea this is an absolute must have feature. Just after a day of using this plugin the Mother Russia is bombing with spam.

![image](https://user-images.githubusercontent.com/1291364/95786538-c76eda00-0ca5-11eb-847d-9c191f5a4c7d.png)

**Comment by bmarshall511** [comment]
Great idea. I'll put this on the roadmap and keep this open to track the progress.
