### ISSUE TITLE
Product reviews from Woocommerce always marked as spam

### ISSUE THREAD

**Issue by janmulder** [bmarshall511/wordpress-zero-spam#230]
In a site using Woocommerce, every product review is marked as spam. 

When the checkbox "Detect Spam/Malicious Comments" is "off", then all reviews are accepted, when "on" all reviews are marked as spam.

Site that demonstrates this failing behavior is: https://www.she-p.com/product/double-connector/ 

Simply try to enter a valid review.

Used versions:

WP: version 5.5.1
Woocommerce: Version 4.6.1
WordPress Zero Spam: Version 4.10.2

**Comment by janmulder** [comment]
A little addition. When a user is logged in, in the Woocommerce shop, any review comment is accepted, and any review comment entered as a guest is refused as spam.

**Comment by Philreely** [comment]
Same here:
Warning: stripslashes() expects parameter 1 to be string, array given in /var/www/mydomain.co.uk/wp-content/plugins/zero-spam/integrations/comments/comments.php on line 244
There was a problem with your submission. Please go back and try again.

**Comment by bmarshall511** [comment]
v5 was just released which should resolve this issue, please let me know if you still run into it.
