### ISSUE TITLE
Is BotScout part of the problem?

### ISSUE THREAD

**Issue by ognik777** [bmarshall511/wordpress-zero-spam#231]
I'm getting emails from BotScout saying it has stopped thousands of spam each day - and I should pay for a premium version.  But the stats in zero spam don't show the traffic BotScout reports.

I have also had a sudden large increase in spam to the email address my contact form uses - since around the same time I installed zero spam.

Now all this sounds pretty unlikely to me, so what should I look at to check it please?

**Comment by bmarshall511** [comment]
BotScout has been done for quite a while now & v5 which was just released has temporarily dropped support for it until they get the site up and running again.
