### ISSUE TITLE
Add WP admin dashboard widgets

### ISSUE THREAD

**Issue by konsti2020** [bmarshall511/wordpress-zero-spam#237]
at the moment the design in combination with mobile devices is not very user-friendly.
It would be better if the pop-up opens as a submenu item or if it is scaled to the screen accordingly.
Also I am missing the charts, they were great as an quick overview. Could they be integrated as a box directly into the WordPress Dashboard?
And it would be handy if you could search the logs by country now that geoblocking is implemented.

**Comment by bmarshall511** [comment]
@konsti2020 Good ideas! Filtering by country will be in the next release. Working on the others.

**Comment by bmarshall511** [comment]
v5.0.5 was just released that includes sorting by country, a few charts & better mobile support. Adding a dashboard widget is on the list.

**Comment by bmarshall511** [comment]
@konsti2020  was just released and now includes a dashboard widget.

Hopefully, that helps you out a bit. If you've got time, could you rate the plugin: https://wordpress.org/plugins/zero-spam/ I'd really appreciate it!
