### ISSUE TITLE
Spam coming through

### ISSUE THREAD

**Issue by intuitiefleven** [bmarshall511/wordpress-zero-spam#240]
We have had the Wordpress zero spam plugin installed on our website for several months and it's been working perfectly. However, since several days it is letting through a lot of spam through our contact form and comments on blogs. Can someone help fix this? 

This is an example:
<img width="386" alt="Screen Shot 2021-02-27 at 09 04 30" src="https://user-images.githubusercontent.com/79756694/109391065-d6fc6180-78da-11eb-87c0-54cf2a09b751.png">

**Comment by bmarshall511** [comment]
I'll need more info. What URL and form is spam coming through on? Have you double-checked the plugin settings to make sure everything is configured properly? What version of the plugin are you running?

**Comment by bmarshall511** [comment]
Closing this, no response and lack of information.
