### ISSUE TITLE
New Types of Spam Getting Through

### ISSUE THREAD

**Issue by SenorFusion** [bmarshall511/wordpress-zero-spam#242]
Over the past few days, the spam bots have seemed to find a new way around WPZeroSpam. We've gone from 1-2 a day hitting spam folder to 100+

The main thing they seem to have in common is dropping spammy comments with spam author name / link that mentions their spam brand in the comment body but NOT using links in the comment body:

![image](https://user-images.githubusercontent.com/1929777/109538647-55e5cb80-7a8e-11eb-944e-3f6f973004ce.png)

**Comment by bmarshall511** [comment]
Can you provide me a URL where the spam is coming through, the plugin version & any other details? Also, please double-check the plugin settings to ensure everything is configured properly.

**Comment by bmarshall511** [comment]
v5.0.8 was just released that includes beefed-up protection for comment forms. Please update to the latest (ensure settings have been configured) and let me know if you're still experiencing this. Closing for now.
