### ISSUE TITLE
WP Forms spam getting through [BUG]

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#245]
https://github.com/bmarshall511/wordpress-zero-spam/issues/241#issuecomment-788193932

**Comment by bmarshall511** [comment]
@rosswintle Do you have Stop Forum Spam enabled?

**Comment by rosswintle** [comment]
No. Should I turn that on?

**Comment by bmarshall511** [comment]
Yeah, give that a try. It performs more checks to determine if a submission is spam & based on those email addresses, feeling pretty strongly they'll be marked as spam once enabled.

**Comment by rosswintle** [comment]
I'll give it a try. But that doesn't answer the question of what changed with the update that caused working spam protection to suddenly stop. Unless stop forum spam was somehow enabled before but not after the update?

**Comment by bmarshall511** [comment]
v4 used both the honeypot method & a on-demand hidden field to determine spam. The on-demand method used JS that injected a hidden field when the form was submitted. v5 doesn't currently have the on-demand method due to issues people were having with valid submissions being marked as spam. Most of the time is was due to JS being turned off, a JS error on the site that was killing the functionality or custom forms that didn't use the same core ID needed to trigger the on-demand method.

With that being said, there are plans to reimplement this on-demand functionality, but in a more full-proof way.

Let me know if enabling Stop Forum Spam helped.

**Comment by bmarshall511** [comment]
Understood, but v5 doesn't say it uses David Walsh's technique. You're right, prior versions did. And yes, reintegrating it is on the roadmap (https://github.com/bmarshall511/wordpress-zero-spam/issues/247). There are several methods to do this for a fool-proof solution, just haven't had time to add it yet.

Closing this for now. Will reopen if WP Forms spam is still getting through using the current detection methods.
