### ISSUE TITLE
Add ability to block specific email domains [FEATURE]

### ISSUE THREAD

**Issue by bmarshall511** [bmarshall511/wordpress-zero-spam#246]
Add an option in settings for a list of email domains (e.g. gmail.com, yahoo.com, etc.) that should be blocked on submissions.

Catching spam isn't 100% no matter what you do, this would allow site admins more control over who gets blocked, especially from spammy domains.

Would be useful if to find an existing list of spammy email domains that could automatically be updated to avoid manual entry.

**Comment by jason-riley** [comment]
A block based on regular expressions would be even more flexible. For example, almost all the spam I receive comes from Gmail accounts with 1 of 5 specific words contained in the email username. Spammers just open new accounts and repeat variants of email addresses using these same keywords. Defining a regular expression would give 100% flexibility, although the email domain block option would still be useful for a broader audience and easier for those who can't write regular expressions.

**Comment by konsti2020** [comment]
Also it would be a nice addition to search the Log not only by IP address but also by E-Mail so you could detect the ones that are used more often.
An alternative would be a grouping function by E-Mail or IP address in the Log.
