### ISSUE TITLE
[BUG]Spam registrations 

### ISSUE THREAD

**Issue by utipparaju** [bmarshall511/wordpress-zero-spam#248]
Hi there

Thank you bery much for the wonderful plugin , it was all worlking fine until latest update

As soon as we had upated to latest version  of WP zero spam few weeks ago , we have been flooded with spam registrations via wordpress login/registration forms and also reset password spam emails

recent Examples as of todays date

New user registration on your site : Username: johnnyswan

New user registration on your site :

Username: blanchehkn

Email: madina.shcherbakova.84@bk.ru

Email: kacalaklo1970@bk.ru

New user registration on your site :

Username: johnnyswan

Email: kacalaklo1970@bk.ru

carrregin43@binfest.info
 b.an.gfit.ersin.a.g.a@gmail.com

![image](https://user-images.githubusercontent.com/80249607/110299540-7e973380-8041-11eb-90de-8fc577c1c785.png)

Please let me know if you can provide more information

Our website  name is pasyanthi.net

Kindly let us know how to resolve ths issue

Many thanks

Usha

**Comment by bmarshall511** [comment]
Have you verified everything has been configured properly in the Zero Spam settings? If so, can you provide the URL of where spam is coming in?

**Comment by utipparaju** [comment]
https://pasyanthi.net/courses/the-16-golden-rules-of-vedic-maths/

https://pasyanthi.net/wp-login.php

https://pasyanthi.net/wp-login.php?action=register

We use custom login page provided by our LMS platform, we have been using same for quite some time and no spam came through and everything was working fine unril latest update

**Comment by bmarshall511** [comment]
Can you shoot me a login so I can look into it? You can email me at me@benmarshall.me

**Comment by bmarshall511** [comment]
Closing since I haven't heard back
