### ISSUE TITLE
Move all pages as tabs under Settings > Zero Spam

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [bmarshall511/wordpress-zero-spam#249]
Hello, Ben!

I'm opening this feature request in relation to this ticket here:
https://wordpress.org/support/topic/move-everything-under-the-settings-page-by-default
I somehow missed your reply, so forgive my delayed response.

WordPress Zero Spam falls in the category of plugins that do things under the hood, with minimal or no input required from the user. Once configured, we don't really need to access it. And this includes the logs. Unless a site is under attack, there is no reason to check them constantly.
Having a dedicated menu link for statistics and logs under the main Dashboard menu only adds clutter to the admin dashboard.
Please consider moving all pages/dashboards as tabs under Settings > Zero Spam. (like in version 3 of the plugin)

If you want to offer people the option of displaying logs and charts under the main Dashboard menu, make it optional.
A checkbox under settings should do the trick.

**Comment by bmarshall511** [comment]
Closing this for now. Many have found this useful and an improvement over the previous version where Zero Spam has its own top-level menu. 

Will reopen if more support for this featured is added to this request.

**Comment by EusebiuOprinoiu** [comment]
Hello, Ben!

You misunderstood!
I'm talking about version 3, when everything was placed under Settings > Zero Spam as tabs.
You're talking about version 4 when you moved Zero Spam to a top-level menu. (I wasn't a fan of that either)
While version 5 is still a slight improvement over version 4, because it dropped the top-level menu, it still feels like a step back from version 3. I hope you change your decision.

As a side note, I have at the moment 6 plugins on my websites that place top-level menus when they shouldn't. I am so frustrated by this that I'm seriously considering making my own plugins to replace them.
