### ISSUE TITLE
Seems to have stopped working [BUG]

### ISSUE THREAD

**Issue by atwamy** [bmarshall511/wordpress-zero-spam#250]
I’ve been using this plugin for a while but it seems to be letting through a lot of spam recently (since the last few updates I think). I’ve checked the settings and selected all that I see relevant but still unfortunately hasn’t stopped. Could someone help please?

**Comment by bmarshall511** [comment]
Please provide the settings, the URL and form where spam is coming through and any 3rd-party form plugins you're using where spam is getting through.

**Comment by atwamy** [comment]
Hi,

This is the form producing spam (the only form on the website) https://www.sureteam.co.uk/contact/tetbury-office/

We use WP forms.

By settings, do you mean the zero spam settings?

***@***.***D726D6.9BCFC260]
***@***.***D726D6.9BCFC260]


Thanks,
Amy




Amy Burton​
Account Manager
***@***.***D726D6.760BCA60]
***@***.******@***.***>
***@***.***D726D6.760BCA60]
01793 766040<tel:01793%20766040>
***@***.***D726D6.760BCA60]
allthingsweb.co.uk<https://www.allthingsweb.co.uk/>
***@***.***D726D6.760BCA60]
[Facebook]<https://www.facebook.com/AllThingsWeb/>
[Instagram]<https://www.instagram.com/allthingsweb/>
[Linked In]<https://www.linkedin.com/company/2469743/>
***@***.***D726D6.760BCA60]<https://www.allthingsweb.co.uk/>
This email and any files transmitted with it are confidential and solely for the use of the individual or entity to whom they are addressed.  The contents should not be disclosed or forwarded to any other person or copies taken.  If you received this email in error, please notify us immediately at ***@***.*** and delete the email from your system.  All Things Web Ltd has taken reasonable precautions to ensure that any attachments to this email have been checked for viruses, however you should complete your own virus checks before opening any attachments as All Things Web Ltd cannot accept any liability for damage sustained as a result of any software virus.  All Things Web® and Allthingsweb® are registered trademarks of All Things Web Ltd Company. Registration No: 06393953  VAT Registration: 824611937.

**Comment by atwamy** [comment]
Hi,

I never heard back on this? The client is now complaining so if I don't hear back by the end of today unfortunately I'm going to have to find something else to keep the client happy.

Thanks,
Amy
________________________________

Amy Burton
Account Manager
***@***.***
01793 766040
allthingsweb.co.uk
This email and any files transmitted with it are confidential and solely for the use of the individual or entity to whom they are addressed.  The contents should not be disclosed or forwarded to any other person or copies taken.  If you received this email in error, please notify us immediately at ***@***.*** and delete the email from your system.  All Things Web Ltd has taken reasonable precautions to ensure that any attachments to this email have been checked for viruses, however you should complete your own virus checks before opening any attachments as All Things Web Ltd cannot accept any liability for damage sustained as a result of any software virus.  All Things Web® and Allthingsweb® are registered trademarks of All Things Web Ltd Company. Registration No: 06393953  VAT Registration: 824611937.
From: Amy Burton
Sent: Thursday, April 1, 2021 9:08 AM
To: bmarshall511/wordpress-zero-spam ***@***.***>; bmarshall511/wordpress-zero-spam ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [bmarshall511/wordpress-zero-spam] Seems to have stopped working [BUG] (#250)


Hi,



This is the form producing spam (the only form on the website) https://www.sureteam.co.uk/contact/tetbury-office/



We use WP forms.



By settings, do you mean the zero spam settings?



***@***.***D726D6.9BCFC260]

***@***.***D726D6.9BCFC260]





Thanks,

Amy









Amy Burton​

Account Manager

***@***.***D726D6.760BCA60]

***@***.******@***.***>

***@***.***D726D6.760BCA60]

01793 766040<tel:01793%20766040>

***@***.***D726D6.760BCA60]

allthingsweb.co.uk<https://www.allthingsweb.co.uk/>

***@***.***D726D6.760BCA60]

[Facebook]<https://www.facebook.com/AllThingsWeb/>

[Instagram]<https://www.instagram.com/allthingsweb/>

[Linked In]<https://www.linkedin.com/company/2469743/>

***@***.***D726D6.760BCA60]<https://www.allthingsweb.co.uk/>

This email and any files transmitted with it are confidential and solely for the use of the individual or entity to whom they are addressed.  The contents should not be disclosed or forwarded to any other person or copies taken.  If you received this email in error, please notify us immediately at ***@***.*** and delete the email from your system.  All Things Web Ltd has taken reasonable precautions to ensure that any attachments to this email have been checked for viruses, however you should complete your own virus checks before opening any attachments as All Things Web Ltd cannot accept any liability for damage sustained as a result of any software virus.  All Things Web® and Allthingsweb® are registered trademarks of All Things Web Ltd Company. Registration No: 06393953  VAT Registration: 824611937.

**Comment by bmarshall511** [comment]
There could be a number of causes, likely your settings haven't been set/strict enough to block those submissions. Please update to the latest version as well to see if it resolves your issue.
