### ISSUE TITLE
All CF7 submissions being blocked [BUG]

### ISSUE THREAD

**Issue by hommealone** [bmarshall511/wordpress-zero-spam#251]
This plugin is blocking ALL attempted CF7 contact form submissions, even very simple messages. I've tried different message content but even one single simple sentence with obviously no spammy words or punctuation gets blocked. CF7 is apparently blocking it because of a match to something in the Disallowed Comment Keys field on the Settings > Discussion page. 

(We do not use Akismet. On some sites we use Google reCaptcha V2, not V3, but we also have the problem on sites without any reCaptcha.)

The only way I can get a submission to go through is to:

    Disable the plugin;
    Delete the content of the Disallowed Comment Keys field on the Settings > Discussion page.

At that point the form can send messages again.

If I re-enable the plugin, the Disallowed Comment Keys field gets re-populated and every submission gets blocked again.

I’ve tried this on several sites I run, on different servers and hosting companies. There is caching on some of the sites but not on others.

I've now had to remove WP Zero Spam from all of these sites but one so the form would function. I have left it in place in one site so that you can see the form and what happens with a submission attempt.

You can see the problem here:
https://www.insitewebsite.com/starter/contact/

The error message you will see is a customized "spam" message set in the CF7 message options.

Is the plugin doing something wrong, or am I? Please let me know what other information I can provide to help with troubleshooting!

**Comment by bmarshall511** [comment]
@hommealone Sorry to hear that. The upcoming release v5.0.12 will include the ability to disable syncing that list. My gut is telling me your CF7 implementation is using that list and maybe something on it that's triggering those messages to fail.

Once released, updated, disable syncing that list, then delete what's there. Let me know if that fixes it for you.

**Comment by hommealone** [comment]
I don't understand... isn't this a serious problem? The CF7 fields are only: Name, Email, Subject, Message. If my subject is just "form test" or "hello from hommealone", and my entire message field is "I like apples and bananas." then nothing in that submission should match your Disallowed Comment Keys list.

In principle, I like the idea of utilizing the Disallowed Comment Keys field, but if your list blocks all messages, doesn't that mean there is something wrong with the list?

Doesn't that suggest that your list is too aggressive and blocking ham instead of just spam?

**Comment by hommealone** [comment]
I've updated to version 5.0.12. In addition to my last question, I see now where the exclusions list is coming from (splorp). Perhaps you could raise a bug request with splorp? I think that would be more helpful coming from you, but let me know if I should file that bug report.

Also, even though the option under General Settings for "Sync Disallowed Keys" is unchecked by default, it doesn't automatically REMOVE the entry that the plugin had put there previously. I had to do that manually. You'll need to make an FAQ or a note in the settings about that.

That said, after updating the plugin *and* deleting the Disallowed Comment Keys entries, I was able to successfully send a message via the CF7 form.

With that "Sync Disallowed Keys" option deselected, is the plugin now providing the same protection that it used to before you integrated the splorp list?

**Comment by bmarshall511** [comment]
Yes, still provides protection
