### ISSUE TITLE
 Spam blocking does not work in WordPress Zero Spam 5.0.x versions [BUG]

### ISSUE THREAD

**Issue by netunia** [bmarshall511/wordpress-zero-spam#252]
Hello,

I have actually stopped working on 3 sites plugin, even the latest update 5.0.12 does not solve the problem. If you roll back to version 4.10.2, the plugin successfully works and blocks spam coming through the forms.

I also tried installing the plugin on a completely clean WordPress 5.7 installation and the result is that WordPress Zero Spam in versions 5.0.x does not work.

All sites have the same configuration
WordPress 5.7
PHP 7.3.27
MySQL 5.7.33

Installed plugins
Admin Menu Editor Pro 2.14.1
Classic Editor 1.6
Cyr-To-Lat 5.0.2
Elementor 3.1.4
Envato Elements 2.0.8
Really Simple SSL 4.0.13
Wordfence Security 7.5.2
WordPress Zero Spam 5.0.12
WPForms Lite 1.6.6
WP Hide & Security Enhancer 1.6.3.4
WP Mail SMTP 2.7.0

I will be grateful for the answer and help.
Thanks!

**Comment by bmarshall511** [comment]
There could be a number of causes, likely your settings haven't been set/strict enough to block those submissions. Please update to the latest version as well to see if it resolves your issue.
