### ISSUE TITLE
[BUG] Update to 5.0.12 lots of spam through Contact Form 7; Rolled back

### ISSUE THREAD

**Issue by cyaburt** [bmarshall511/wordpress-zero-spam#253]
**Describe the bug**
Wordpress Zero Spam had been working great and the majority of spam was not getting through with the exception of our targeted spam emails which I had blocked by keywords in Settings. I have WP Zero Spam on 8 corporate sites and updated each of these. Now we are receiving spam through all of these. Some are blocked by Barracuda, but others are not.

I have rolled back each of our sites to v 5.0.8. Each site is set the same. We do not have Comments on any of our sites. David Walsh is not enabled. Snapshots are attached.

**Expected behavior**
This is to advise you there is an issue. We try to keep all plugins up-to-date and will update WordPress as soon as everything is compatible so we don't break our sites or look for alternatives. 

Our sites are running on:
WordPress 5.6.2
PHP 7.3
Beaver Builder Pro 2.4.2.2
Beaver Builder Theme 1.7.8
Asset Clean-Up 1.3.7.7
Classic Editor 1.6
Contact Form 7 5.4
Flamingo 2.2.1
Imagify 1.9.14
Jetpack 9.6
Rank Math SEO 1.0.61.1
Really Simple SSL & Pro 4.0.13 & 4.1.7
Vaultpress 2.1.4
Wordfence 7.5.2
WP Rocket 3.8.8
WP Zero Spam rolled back to 5.0.8

**Snapshots**
Snapshots are attached from our different sites from Flamingo including the ip addresses.

![CSI spam](https://user-images.githubusercontent.com/82383926/114396811-ff2edf80-9b6b-11eb-839f-44409916bfdf.png)
![CSI spam advertising](https://user-images.githubusercontent.com/82383926/114396812-ff2edf80-9b6b-11eb-83dd-c827d28a7780.png)
![COI spam](https://user-images.githubusercontent.com/82383926/114396813-ff2edf80-9b6b-11eb-8481-96d87eb59d91.png)
![CGI spam Trustpilot](https://user-images.githubusercontent.com/82383926/114396814-ff2edf80-9b6b-11eb-9df3-3ed1799ae46e.png)
![CEI software](https://user-images.githubusercontent.com/82383926/114396816-ffc77600-9b6b-11eb-92a8-b8bd51b07e81.png)

**Comment by bmarshall511** [comment]
There could be a number of causes, likely your settings haven't been set/strict enough to block those submissions. Please update to the latest version as well to see if it resolves your issue.
