### ISSUE TITLE
Unnecessary calls to ipstack

### ISSUE THREAD

**Issue by jason-riley** [bmarshall511/wordpress-zero-spam#255]
I have just installed Zero Spam and have 4 blocked IP addresses in the log, yet hundreds of calls to the ipstack API. Given the ipstack API is ONLY used to provide geolocation for reporting of BLOCKED IP addresses, there should only be 4 API calls to ipstack. Instead it appears to be calling ipstack for every user visit, using an unnecessary amount of IP calls. Zero Spam should only be calling the ipstack API for IP addresses that are being blocked, not every page visit, should it not?

**Comment by bmarshall511** [comment]
Closing, need more information.

**Comment by MACscr** [comment]
im going to reopen this as i have the same issue with ipinfo. Even worse, its using 20k api calls when only 3500 of the ip's are unique. caching is setup for 14 days. With that said, as the original poster mentioned, the calls should only be made in the admin and only for blocked ip's and for those reports? Obviously that doesnt need to be done on thy fly and should simply be done when the ip is logged as blocked. Why would something be done on page load?
