### ISSUE TITLE
[FEATURE] HTTP_CF_IPCOUNTRY / X-FORWARDED-COUNTRY support

### ISSUE THREAD

**Issue by ash-f** [bmarshall511/wordpress-zero-spam#267]
Would be nice if you could support HTTP_CF_IPCOUNTRY / HTTP_X_FORWARDED_COUNTRY or equivalent thing that uses a server env to detect country.

**Comment by ash-f** [comment]
Sure.

**Comment by ash-f** [comment]
Would be nice if I could set custom env name.
X-FORWARDED-COUNTRY is used on Cloudways which is popular managed cloud VPS.

**Comment by bmarshall511** [comment]
@ash-f I'll look into it, could you create another feature request so I don't forget and you can track the progress of it?

And thanks for the review!
