### ISSUE TITLE
How to understand who is blocking the site? zero spam

### ISSUE THREAD

**Issue by matteoraggi** [bmarshall511/wordpress-zero-spam#269]
If I get this error when I go to the website: Your IP address has been blocked by WordPress Zero Spam due to detected spam/malicious activity.
How can I know if the error comes from zerospam, or from David Walsh Technique or from Stop Forum Spam or from ipstack etc.. ?

**Comment by bmarshall511** [comment]
Enabled logging, then view the Zero Spam dashboard under the Dashboard admin menu.
