### ISSUE TITLE
Are there any CLI options to enable plugin settings?

### ISSUE THREAD

**Issue by kmob2** [bmarshall511/wordpress-zero-spam#271]
Hello,

I'm about to install the WordPress Zero Spam plugin on ~100 websites. I'm installing the plugin via CLI, however, I noticed that out of the box, the plugins spam features are all disabled and need to be manually enabled via the plugins settings page.

Are there any CLI options available to enable/disable certain settings, such as `Zero Spam | Enabled`, `Protect Comments | Enabled`, `David Walsh Technique | Enabled` etc.

Thank you.

**Comment by bmarshall511** [comment]
@kmob2 Great idea! I'll work on this and get included in the next release.

**Comment by bmarshall511** [comment]
@kmob2 v5.1.1 was just released and included WP-CLI commands:

`wp zerospam autoconfigure` — Auto-configures with recommended settings.
`wp zerospam settings` — Displays all plugin settings.
`wp zerospam set --[SETTING_KEY]=[VALUE]` — Updates a plugin setting.

Hopefully, that helps you out a bit. If you've got time, could you rate the plugin: https://wordpress.org/plugins/zero-spam/ I'd really appreciate it!
