### ISSUE TITLE
Version 5.1.1 breaks dashboard widgets for WPForms and WP Mail SMTP plugins

### ISSUE THREAD

**Issue by jason-riley** [bmarshall511/wordpress-zero-spam#272]
**Describe the bug**
Using version 5.1.1 interferes with the dashboard widget charts for both the WPForms and WP Mail SMTP plugins. The charts no longer render history of email sends/receives and form submissions, and the labels and legends appear incorrectly. There appears to be a conflict in CSS used by WordPress Zero Spam and WPForms/WP Mail SMTP.

**To Reproduce**
Install WP Forms and WP Mail SMTP with WordPress Zero Spam

**Expected behavior**
Charts, legends and labels to render correctly in WPForms and WP Mail SMTP plugins.

**Screenshots**
Before shows how the widgets should appear. After shows how the same widgets appear when WordPress Zero Spam 5.1.1 is active.

<img width="589" alt="after" src="https://user-images.githubusercontent.com/29963056/139754348-6f5496f5-185e-43f2-96b0-68784236dcf5.png">
<img width="591" alt="before" src="https://user-images.githubusercontent.com/29963056/139754354-4177cafa-8f04-43c4-9c76-49c4c7afc40d.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.0.1
 - Browser Chrome
 - Version 95

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by bmarshall511** [comment]
@jason-riley Looks like you need the pro versions of those plugins to view the charts on the dashboard and I don't have those. Maybe you can help me narrow it down, are you seeing any JS errors in the browser console?

**Comment by jason-riley** [comment]
`jquery.min.js?ver=3.6.0:2 jQuery.Deferred exception: Cannot set properties of undefined (setting 'offset') TypeError: Cannot set properties of undefined (setting 'offset')
at Object.updateStyle (https://[domain]/wp-content/plugins/wp-mail-smtp-pro/assets/pro/js/smtp-pro-dashboard-widget.min.js?ver=3.1.0:1:7768)
at Object.updateUI (https://[domain]/wp-content/plugins/wp-mail-smtp-pro/assets/pro/js/smtp-pro-dashboard-widget.min.js?ver=3.1.0:1:3320)
at Object.init (https://[domain]/wp-content/plugins/wp-mail-smtp-pro/assets/pro/js/smtp-pro-dashboard-widget.min.js?ver=3.1.0:1:2584)
at HTMLDocument.ready (https://[domain]/wp-content/plugins/wp-mail-smtp-pro/assets/pro/js/smtp-pro-dashboard-widget.min.js?ver=3.1.0:1:8686)
at e (https://[domain]/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:30038)
at t (https://[domain]/wp-includes/js/jquery/jquery.min.js?ver=3.6.0:2:30340) undefined
S.Deferred.exceptionHook @ jquery.min.js?ver=3.6.0:2
jquery.min.js?ver=3.6.0:2 Uncaught TypeError: Cannot set properties of undefined (setting 'offset')
at Object.updateStyle (smtp-pro-dashboard-widget.min.js?ver=3.1.0:1)
at Object.updateUI (smtp-pro-dashboard-widget.min.js?ver=3.1.0:1)
at Object.init (smtp-pro-dashboard-widget.min.js?ver=3.1.0:1)
at HTMLDocument.ready (smtp-pro-dashboard-widget.min.js?ver=3.1.0:1)
at e (jquery.min.js?ver=3.6.0:2)
at t (jquery.min.js?ver=3.6.0:2)`

**Comment by bmarshall511** [comment]
@jason-riley Looks like those are all related to WP Mail SMTP Pro, nothing getting reported with ZS's implementation. I'd start with contacting their support. Likely a conflict with the JS implementation of Chart.js, but can't really tell without being able to replicate it myself.

I can say ZS's implementation is standard & doesn't customize the default CSS or JS. The JS for our chart is also self-contained so *shouldn't cause any issues, but again, can't say with 100% certainty without being able to replicate.

If there are any other details or a testing environment I could access to replicate, I'd be happy to look into it more. Closing for now, but will reopen if more info becomes available that shows a conflict with ZS's chart.

**Comment by jason-riley** [comment]
Those errors only occur when Zero Spam 5.1.1 plugin is active. They don't appear when teh plugin is disabled, and they also don't appear when using Zero Spam 5.1.0 - the errors only occur when Zero Spam 5.1.1 is installed. I am seeing the same issue across multiple websites.

**Comment by bmarshall511** [comment]
Understood & wish I could help, but like a car mechanic, I can't fix something I can't replicate. And it would make sense both of those plugins work together since their put out but the same company, doesn't mean their implementation is correct and since the error is coming from WP Mail SMTP Pro. Again, I'd contact their support or just disable the ZS dashboard widget unless you can provide me with more details or a testing environment where I can replicate it.
