### ISSUE TITLE
Disable widget for subscribers account [FEATURE]

### ISSUE THREAD

**Issue by TheMenethil** [bmarshall511/wordpress-zero-spam#275]
Hello !
My subscribers have a widget panel for Zero Spam. It's not useful for them but only for admin. There is no options to disable that for all subscribers accounts.

**Comment by bmarshall511** [comment]
@TheMenethil Release is up, hope this accomplishes what you need.

If you have time, could you rate the plugin: https://wordpress.org/plugins/zero-spam/, I'd really appreciate it!
