### ISSUE TITLE
[FEATURE] Fluent Forms? seems to be disabled somehow

### ISSUE THREAD

**Issue by ash-f** [bmarshall511/wordpress-zero-spam#276]
I see the Fluent Forms module in the plugin folder.
But also I see it's commented out in /includes/class-plugin.php.
Is it intentionally disabled for some reason?
Or Fluent Forms does not need this module?

**Comment by bmarshall511** [comment]
@ash-f It was once integrated, but they released an update a while back that uses a couple of different methods to prevent spam submissions, similar to Zero Spam, and unfortunately made it more difficult to hook into submissions to integrate Zero Spam's protection. It's commented out for now until I get some more time to devote to digging in alternative ways to integrate it. I'll leave this issue open so the progress can be tracked.

**Comment by bmarshall511** [comment]
Hey @ash-f, good news! This will be re-enabled with the next release.

**Comment by ash-f** [comment]
Thank you for the quick update.

**Comment by ash-f** [comment]
I can turn off Fluent's built-in honeypot if it might become a cause of trouble.
Zero Spam does work well so I don't need built-in feature in this case.
Is it safer to disable built-in honeypot?

**Comment by bmarshall511** [comment]
shouldn't cause any trouble, just double protection using the honeypot technique.
