### ISSUE TITLE
Error (class-admin.php line 50: Argument #2 must be of type array, bool given) in version 5.1.5

### ISSUE THREAD

**Issue by lquidfire** [bmarshall511/wordpress-zero-spam#277]
I received the following error on my WP site after the latest update to version 5.1.5:

`An error of type E_ERROR was caused in line 50 of the file [redacted]/public_html/wp-content/plugins/zero-spam/core/admin/class-admin.php. Error message: Uncaught TypeError: array_intersect(): Argument #2 must be of type array, bool given in [redacted]/public_html/wp-content/plugins/zero-spam/core/admin/class-admin.php:50 Stack trace: #0 [redacted]/public_html/wp-content/plugins/zero-spam/core/admin/class-admin.php(50): array_intersect() #1 [redacted]/public_html/wp-includes/class-wp-hook.php(303): ZeroSpam\Core\Admin\Admin->register_dashboard_widget() #2 [redacted]/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #3 [redacted]/public_html/wp-includes/plugin.php(470): WP_Hook->do_action() #4 [redacted]/public_html/wp-admin/includes/dashboard.php(129): do_action() #5 [redacted]/public_html/wp-admin/index.php(15): wp_dashboard_setup() #6 {main} thrown`

**Comment by bmarshall511** [comment]
@lquidfire Thanks for letting me know! It'll be fixed in the next release. Until then, if you save settings, with a Dashboard Widget Visibility role selected, it should resolve the issue.

**Comment by bmarshall511** [comment]
v5.1.6 was just released and includes this fix.

**Comment by lquidfire** [comment]
Thanks for the very quick work-around and then the quick fix. Much appreciated!

**Comment by bmarshall511** [comment]
@lquidfire No problem, glad I was able to get the fix up quick. 

If you've got time, would you mind reviewing the plugin: https://wordpress.org/plugins/zero-spam/. I'd really appreciate it!
