### ISSUE TITLE
[BUG] User Login Integration breaks WooCommerce Login

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [bmarshall511/wordpress-zero-spam#280]
Hello, Ben.

When the User Login Integration is enabled, the login forms created by WooCommerce no longer work.
(customers are blocked from logging in)

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu Can you provide details of the block, what it's failing?

**Comment by EusebiuOprinoiu** [comment]
I'm not really sure what you mean by "details of the block".
I'm referring to the login form created by the `[woocommerce_my_account]` shortcode.
When User Login Integration is enabled, WordPress Zero Spam blocks all login attempts and displays the error message configured in the plugin settings above the form.
People can login without issues using the native WordPress login page, on `/wp-admin`.

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu I found the issue. For future reference, you can view details on blocks via Admin > Dashboard > Zero Spam > Logs and then click on the Details button. I'll get a fix pushed up.

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu v5.2.1 has been released for this fix.

**Comment by EusebiuOprinoiu** [comment]
Thank you! That was fast! :)
