### ISSUE TITLE
[BUG] PHP errors with Zero Spam v5.2.2

### ISSUE THREAD

**Issue by Dhwty** [bmarshall511/wordpress-zero-spam#282]
**Describe the bug**
This afternoon, I updated from v5.1.4 to v5.2.2. Immediately afterward, I began getting the following error about six or seven times at the top of every page on the site:

> Warning: ftp_fget() expects parameter 1 to be resource, null given in /home/public/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146

Disabling the plugin via SSH caused the errors to stop, after a hard refresh. (PHP errors prevent logins on WP, so the admin panel became temporarily inaccessible.)

No other changes were made to the site between it loading properly and throwing this error. No changes besides disabling the plugin were necessary to make it stop erroring. I'll be rolling back to 5.1.4 until the next release.

**To Reproduce**
Presumably, one would be able to reproduce this by upgrading from v5.1.4 to v5.2.2 on WP 5.8.2, but since I'm the first one reporting it, I'm gonna guess that's not actually the problem.

**Expected behavior**
I expected the updated plugin to continue working in the background, as it always does, without throwing errors.

**Screenshots**
Screenshots seem like overkill.

**Server:**
 - Architecture: FreeBSD 12.2-RELEASE-p6 amd64
 - Web Server: Apache 
 - PHP: 7.3.29
- WordPress: 5.8.2
- HTTPS: enabled
(Let me know if there are other specs that would help diagnose this.)

**Additional context**

**Comment by bmarshall511** [comment]
Closing, this is addressed in the plugin FAQ and an issue with how some hosts use the filesystem. There's an easy fix by adding a constant in your wp-config.php file: `define('FS_METHOD', 'direct');`

See https://pantheon.io/docs/plugins-known-issues#define-fs_method for more info.
