### ISSUE TITLE
Create integration with Memberpress registration forms [FEATURE]

### ISSUE THREAD

**Issue by wholebiz** [bmarshall511/wordpress-zero-spam#283]
Per discussion with Ben, adapt Zero Spam to work with Memberpress free and paid registration forms. Plugin copy submitted via email.

**Comment by bmarshall511** [comment]
For reference, here are the plugin's available hooks: https://docs.memberpress.com/article/325-action-hooks-in-memberpress

**Comment by bmarshall511** [comment]
@wholebiz Good news! Found some time and got this added for the registration forms. Was just released in v5.2.4.
