### ISSUE TITLE
[FEATURE] Allow Memberpress users to select registration membership level registration forms for ZeroSpam deployment. ZeroSpam should be disabled if form is accessed in the logged-in state.

### ISSUE THREAD

**Issue by wholebiz** [bmarshall511/wordpress-zero-spam#288]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bmarshall511** [comment]
@wholebiz Zero Spam detection methods don't run for logged-in users, closing.

**Comment by wholebiz** [comment]
Great. 

What about "Allow Memberpress users to select registration membership level registration forms for ZeroSpam deployment" ?

**Comment by bmarshall511** [comment]
@wholebiz Could you create a new feature request and be sure to fill out the details & specifics vs. adding everything in the title. Also, clarify what you mean by 'ZerosSpam deployment'. Assuming the ask is allow admins to select which 'Membership' (`memberpressproduct`) post should have Zero Spam protection.
