### ISSUE TITLE
Database Errors on Activation

### ISSUE THREAD

**Issue by shazahm1** [bmarshall511/wordpress-zero-spam#80]
On initial activation with Query Monitor enabled I get the following db errors:

SELECT *
FROM wp_zerospam_blocked_ips    Zero_Spam->_ip_check()
Zero_Spam->__construct()    Plugin: zero-spam   Table '{redacted}_sandbox.wp_zerospam_blocked_ips' doesn't exist
DESCRIBE wp_zerospam_log;   Zero_Spam->plugins_loaded()
do_action('plugins_loaded') Plugin: zero-spam   Table '{redacted}_sandbox.wp_zerospam_log' doesn't exist
DESCRIBE wp_zerospam_blocked_ips;   Zero_Spam->plugins_loaded()
do_action('plugins_loaded') Plugin: zero-spam   Table '{redacted}_sandbox.wp_zerospam_blocked_ips' doesn't exist

I see you just released 1.5.1, so maybe this is already fixed but I didn't see it in the changelog...

**Comment by davdebcom** [comment]
FYI:
https://wordpress.storelocatorplus.com/turn-off-dbdelta-describe-errors/

**Comment by bmarshall511** [comment]
Fixed: https://github.com/bmarshall511/wordpress-zero-spam/pull/148
